Updating README with formatting and adding tips
loblaw-sre/backstage-plugin-gitlab pull request #1
Opened 2021-08-19 04:15 UTC by NishkarshRaj

Love this addition to the Backstage Project, I tested it out on my local project and wanted to make sure that the Documentation is more readable and understandable to people who are new with Backstage and its underlying technology

2021-09-01 12:19 UTC, mufaddal7 approved these changes

2021-09-02 12:41 UTC, satrox28 requested changes

2021-09-02 12:41 UTC, satrox28 commented on README.md
> +```yml
It need to be changed to yaml.

2021-09-03 03:12 UTC, NishkarshRaj commented
@satrox28 did a rebase to be in sync with the repository and resolved the requested changes. Please Review 👍

2021-09-03 11:29 UTC, satrox28 approved these changes

2021-09-03 11:29 UTC, merged

2021-09-03 11:30 UTC, satrox28 commented
Have merged the changes, thanks for your contribution  @NishkarshRaj