Update core-components and core-plugin-api
loblaw-sre/backstage-plugin-gitlab pull request #67
Opened 2022-01-12 15:47 UTC by mscam

While updating my backstage monorepos installation to latest version (0.4.11) I noticed those packages are not updated because this plugin still use old versions:

@backstage/core-components @ ^0.7.1 should be changed to ^0.8.3
@backstage/core-plugin-api @ ^0.1.3 should be changed to ^0.4.1

2022-01-13 19:51 UTC, satrox28 commented
Hi @mscam  thanks for using the Gitlab Plugin. Sure, we will upgrade it.

2022-01-15 12:15 UTC, mscam commented
Thank you @satrox28, please let me know if you need testing or any help in the process

2022-01-17 17:39 UTC, satrox28 reviewed
@backstage/core-plugin-api": "^0.5.0 is available now @mscam

2022-01-18 12:04 UTC, mscam commented
@satrox28 I have bumped @backstage/core-plugin-api to v0.5.0. Is there any other change required?

2022-01-18 12:11 UTC, satrox28 commented
Thanks for updating it @mscam, can you sign all the commits too https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

2022-01-18 14:49 UTC, mscam commented
@satrox28 commits are now rebased and signed. I don't have the possibility right now to test the changes on a local installation, so please let me know if everything works as expected.

2022-01-18 16:46 UTC, satrox28 commented
Hi @mscam thanks have tested it and its working as expected.

2022-01-18 16:47 UTC, satrox28 approved these changes
The changes looks good, thanks.

2022-01-18 17:19 UTC, satrox28 requested changes
signing is missing, can you check and run below command.

git commit --amend --signoff

2022-01-18 20:08 UTC, mscam commented
Unfortunately, it looks like updating the package version was not enough.

![Uploading Screenshot 2022-01-18 at 21.07.24.png…]()

Can you please assist on updating the plugin code to run with backstage latest? 


Thanks 🙏

2022-01-18 21:37 UTC, mscam commented
I tested it now and it works fine with backstage latest (version 0.4.12) @satrox28

2022-01-18 21:54 UTC, satrox28 approved these changes
Thanks, changes looks good. Approved @mscam

2022-01-18 22:58 UTC, merged

2022-01-19 17:16 UTC, mscam commented
thanks 🙏  when it will be released?

2022-01-21 03:33 UTC, satrox28 commented
Hi @mscam it will be released on 01/21.

2022-01-21 22:06 UTC, satrox28 commented
We have released 0.1.17 @mscam